FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache tzdata
ENV TZ=Asia/Ho_Chi_Minh

COPY package.json .

RUN npm install express http-proxy-middleware

COPY dist ./dist

COPY server.js .

EXPOSE 80

CMD ["node", "server.js"]
