FROM python:3.9-slim

WORKDIR /app

# Cài đặt công cụ mạng và CÔNG CỤ BIÊN DỊCH (gcc, python3-dev)
# netifaces cần gcc để cài đặt
RUN apt-get update && apt-get install -y \
    network-manager \
    iproute2 \
    gcc \
    libc-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Cài thư viện Python
RUN pip install flask flask-cors netifaces

COPY network_api.py .

EXPOSE 5000

CMD ["python", "network_api.py"]
