FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

# Copy frontend JAR
COPY bms-frontend.jar /app/app.jar

# Port used by this JAR inside the container
EXPOSE 8080

ENV JAVA_OPTS=""

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
